# Generated by Django 5.0.4 on 2024-04-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image',
            new_name='imagine',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='nume',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='pret',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_sold',
            new_name='vandut',
        ),
    ]
