# Generated by Django 5.0.4 on 2024-04-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_rename_category_item_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categorie',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='descriere',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='imagine',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='vandut',
            new_name='is_sold',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='nume',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='pret',
            new_name='price',
        ),
    ]
